// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cliReq.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lspb {

  /// <summary>Holder for reflection information generated from cliReq.proto</summary>
  public static partial class CliReqReflection {

    #region Descriptor
    /// <summary>File descriptor for cliReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CliReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxjbGlSZXEucHJvdG8SBGxzcGIaDGxzRW51bS5wcm90bxoPZ2FtZVByb3Rv",
            "LnByb3RvItkBCgZDbGlSZXESDgoGdXNlcklkGAEgASgFEiAKCG1vZHVsZUlk",
            "GAIgASgOMg4ubHNwYi5Nb2R1bGVJZBIlCghtZXRob2RJZBgDIAEoDjITLmxz",
            "cGIuQ2xpZW50TXNnVHlwZRIoCgxjbGlFbnRlclJvb20YZSABKAsyEi5sc3Bi",
            "LkNsaUVudGVyUm9vbRImCgtjbGlJbml0T3ZlchhmIAEoCzIRLmxzcGIuQ2xp",
            "SW5pdE92ZXISJAoKY2xpT3BlcmF0ZRhnIAEoCzIQLmxzcGIuQ2xpT3BlcmF0",
            "ZSpXCg1DbGllbnRNc2dUeXBlEhMKD2Vycm9yQ2xpZW50VHlwZRAAEhAKDGNs",
            "aUVudGVyUm9vbRBlEg8KC2NsaUluaXRPdmVyEGYSDgoKY2xpT3BlcmF0ZRBn",
            "QhIKEG9yZy5icm8ubHNzcnYucGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Lspb.LsEnumReflection.Descriptor, global::Lspb.GameProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lspb.ClientMsgType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Lspb.CliReq), global::Lspb.CliReq.Parser, new[]{ "UserId", "ModuleId", "MethodId", "CliEnterRoom", "CliInitOver", "CliOperate" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ClientMsgType {
    /// <summary>
    ///* default 
    /// </summary>
    [pbr::OriginalName("errorClientType")] ErrorClientType = 0,
    /// <summary>
    ///* 进入游戏 
    /// </summary>
    [pbr::OriginalName("cliEnterRoom")] CliEnterRoom = 101,
    /// <summary>
    ///* 通知服务器初始化完成 
    /// </summary>
    [pbr::OriginalName("cliInitOver")] CliInitOver = 102,
    /// <summary>
    ///* 客户端对坦克的具体操作 
    /// </summary>
    [pbr::OriginalName("cliOperate")] CliOperate = 103,
  }

  #endregion

  #region Messages
  /// <summary>
  ///* 所有上行请求都是clientRequest，服务器根据methodId读取具体的message内容,当 
  /// </summary>
  public sealed partial class CliReq : pb::IMessage<CliReq> {
    private static readonly pb::MessageParser<CliReq> _parser = new pb::MessageParser<CliReq>(() => new CliReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CliReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Lspb.CliReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CliReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CliReq(CliReq other) : this() {
      userId_ = other.userId_;
      moduleId_ = other.moduleId_;
      methodId_ = other.methodId_;
      CliEnterRoom = other.cliEnterRoom_ != null ? other.CliEnterRoom.Clone() : null;
      CliInitOver = other.cliInitOver_ != null ? other.CliInitOver.Clone() : null;
      CliOperate = other.cliOperate_ != null ? other.CliOperate.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CliReq Clone() {
      return new CliReq(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private int userId_;
    /// <summary>
    ///* 用户名 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "moduleId" field.</summary>
    public const int ModuleIdFieldNumber = 2;
    private global::Lspb.ModuleId moduleId_ = 0;
    /// <summary>
    ///* 请求模块 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Lspb.ModuleId ModuleId {
      get { return moduleId_; }
      set {
        moduleId_ = value;
      }
    }

    /// <summary>Field number for the "methodId" field.</summary>
    public const int MethodIdFieldNumber = 3;
    private global::Lspb.ClientMsgType methodId_ = 0;
    /// <summary>
    ///* 请求方法名 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Lspb.ClientMsgType MethodId {
      get { return methodId_; }
      set {
        methodId_ = value;
      }
    }

    /// <summary>Field number for the "cliEnterRoom" field.</summary>
    public const int CliEnterRoomFieldNumber = 101;
    private global::Lspb.CliEnterRoom cliEnterRoom_;
    /// <summary>
    ///* 进入房间 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Lspb.CliEnterRoom CliEnterRoom {
      get { return cliEnterRoom_; }
      set {
        cliEnterRoom_ = value;
      }
    }

    /// <summary>Field number for the "cliInitOver" field.</summary>
    public const int CliInitOverFieldNumber = 102;
    private global::Lspb.CliInitOver cliInitOver_;
    /// <summary>
    ///* 客户端初始化完成 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Lspb.CliInitOver CliInitOver {
      get { return cliInitOver_; }
      set {
        cliInitOver_ = value;
      }
    }

    /// <summary>Field number for the "cliOperate" field.</summary>
    public const int CliOperateFieldNumber = 103;
    private global::Lspb.CliOperate cliOperate_;
    /// <summary>
    ///* 客户端对坦克的具体操作 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Lspb.CliOperate CliOperate {
      get { return cliOperate_; }
      set {
        cliOperate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CliReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CliReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (ModuleId != other.ModuleId) return false;
      if (MethodId != other.MethodId) return false;
      if (!object.Equals(CliEnterRoom, other.CliEnterRoom)) return false;
      if (!object.Equals(CliInitOver, other.CliInitOver)) return false;
      if (!object.Equals(CliOperate, other.CliOperate)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0) hash ^= UserId.GetHashCode();
      if (ModuleId != 0) hash ^= ModuleId.GetHashCode();
      if (MethodId != 0) hash ^= MethodId.GetHashCode();
      if (cliEnterRoom_ != null) hash ^= CliEnterRoom.GetHashCode();
      if (cliInitOver_ != null) hash ^= CliInitOver.GetHashCode();
      if (cliOperate_ != null) hash ^= CliOperate.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UserId);
      }
      if (ModuleId != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ModuleId);
      }
      if (MethodId != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MethodId);
      }
      if (cliEnterRoom_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(CliEnterRoom);
      }
      if (cliInitOver_ != null) {
        output.WriteRawTag(178, 6);
        output.WriteMessage(CliInitOver);
      }
      if (cliOperate_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(CliOperate);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
      }
      if (ModuleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ModuleId);
      }
      if (MethodId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MethodId);
      }
      if (cliEnterRoom_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CliEnterRoom);
      }
      if (cliInitOver_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CliInitOver);
      }
      if (cliOperate_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CliOperate);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CliReq other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0) {
        UserId = other.UserId;
      }
      if (other.ModuleId != 0) {
        ModuleId = other.ModuleId;
      }
      if (other.MethodId != 0) {
        MethodId = other.MethodId;
      }
      if (other.cliEnterRoom_ != null) {
        if (cliEnterRoom_ == null) {
          cliEnterRoom_ = new global::Lspb.CliEnterRoom();
        }
        CliEnterRoom.MergeFrom(other.CliEnterRoom);
      }
      if (other.cliInitOver_ != null) {
        if (cliInitOver_ == null) {
          cliInitOver_ = new global::Lspb.CliInitOver();
        }
        CliInitOver.MergeFrom(other.CliInitOver);
      }
      if (other.cliOperate_ != null) {
        if (cliOperate_ == null) {
          cliOperate_ = new global::Lspb.CliOperate();
        }
        CliOperate.MergeFrom(other.CliOperate);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UserId = input.ReadInt32();
            break;
          }
          case 16: {
            moduleId_ = (global::Lspb.ModuleId) input.ReadEnum();
            break;
          }
          case 24: {
            methodId_ = (global::Lspb.ClientMsgType) input.ReadEnum();
            break;
          }
          case 810: {
            if (cliEnterRoom_ == null) {
              cliEnterRoom_ = new global::Lspb.CliEnterRoom();
            }
            input.ReadMessage(cliEnterRoom_);
            break;
          }
          case 818: {
            if (cliInitOver_ == null) {
              cliInitOver_ = new global::Lspb.CliInitOver();
            }
            input.ReadMessage(cliInitOver_);
            break;
          }
          case 826: {
            if (cliOperate_ == null) {
              cliOperate_ = new global::Lspb.CliOperate();
            }
            input.ReadMessage(cliOperate_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
