// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lsEnum.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Lspb {

  /// <summary>Holder for reflection information generated from lsEnum.proto</summary>
  public static partial class LsEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for lsEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LsEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxsc0VudW0ucHJvdG8SBGxzcGIqJgoITW9kdWxlSWQSEAoMVW5rbm93bk1v",
            "ZGVsEAASCAoER2FtZRABKj4KBlJlc3VsdBILCgdzdWNjZXNzEAASBwoDZXJy",
            "EAESDwoLZXJyTm9NZXRob2QQAhINCgllcnJOdWxNc2cQA0ISChBvcmcuYnJv",
            "Lmxzc3J2LnBiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Lspb.ModuleId), typeof(global::Lspb.Result), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ModuleId {
    /// <summary>
    ///* default 
    /// </summary>
    [pbr::OriginalName("UnknownModel")] UnknownModel = 0,
    /// <summary>
    ///* game 
    /// </summary>
    [pbr::OriginalName("Game")] Game = 1,
  }

  public enum Result {
    /// <summary>
    ///* 成功 
    /// </summary>
    [pbr::OriginalName("success")] Success = 0,
    /// <summary>
    ///* 任意失败 
    /// </summary>
    [pbr::OriginalName("err")] Err = 1,
    /// <summary>
    ///* 没有该方法错误 
    /// </summary>
    [pbr::OriginalName("errNoMethod")] ErrNoMethod = 2,
    /// <summary>
    ///* 消息为空 
    /// </summary>
    [pbr::OriginalName("errNulMsg")] ErrNulMsg = 3,
  }

  #endregion

}

#endregion Designer generated code
